Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-05ff5eaef6149df49 # Amazon Linux AMA
      Tags:
        - Key: "Name"
          Value: !Join [" ",[ EC2, instance, for , !Ref AWS::Region]] # Using a function and pseudo parameter
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH Access for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0